apiVersion: backstage.io/v1alpha1
kind: Environment
metadata:
  name: dev
  description: "testing..........."
  members: ["default:user/shreejit.bhattacharyya"]
spec:
  belongsTo: project1
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
